name: Build AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node correto
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build web
        run: npm run build

      # Java CORRETO (resolve seu erro)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Android SDK
      - name: Setup Android
        uses: android-actions/setup-android@v3

      # Capacitor sync
      - name: Sync Capacitor
        run: npx cap sync android

      # Build do AAB
      - name: Build AAB
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease

      # Upload (VERSÃO CORRIGIDA)
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release.aab
